import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { runCli } from "../src/cli/main.js";
import {
  handleOpenSequence,
  handleRenderDigestGel,
  importSequenceFile,
  MAX_GEL_SAMPLE_BANDS,
  renderDigestGel,
  simulateDigest,
  type ToolResultEnvelope,
} from "../src/index.js";
import { stageFixture } from "./support/fixtures.js";

async function tempWorkspaceDir(): Promise<string> {
  return fs.mkdtemp(path.join(os.tmpdir(), "mol-gel-"));
}

async function createWorkspace(): Promise<{ workspaceDir: string; workspacePath: string }> {
  const workspaceDir = await tempWorkspaceDir();
  const inputPath = path.join(workspaceDir, "input.fa");
  await fs.writeFile(inputPath, ">gel\nACGTACGTACGT\n", "utf8");
  const opened = await handleOpenSequence({
    inputPath,
    workspaceDir,
    format: "fasta",
    moleculeId: "mol_gel",
  });
  expect(opened.ok).toBe(true);
  return { workspaceDir, workspacePath: path.join(workspaceDir, "molecule.workspace.json") };
}

async function importPuc19(): Promise<{ workspaceDir: string; workspacePath: string; moleculeId: string }> {
  const workspaceDir = await tempWorkspaceDir();
  const result = await importSequenceFile({
    inputPath: await stageFixture(workspaceDir, "genbank/puc19.gb"),
    workspaceDir,
    format: "genbank",
    moleculeId: "mol_puc19",
  });
  return { workspaceDir, workspacePath: result.workspacePath, moleculeId: result.moleculeIds[0] };
}

describe("digest gel rendering", () => {
  it("writes a deterministic log-scaled SVG gel artifact", async () => {
    const { workspaceDir, workspacePath } = await createWorkspace();
    const result = await renderDigestGel(
      workspacePath,
      "gel_math",
      [
        {
          label: "Digest",
          fragments: [
            { size: 100, label: "small" },
            { size: 1000, label: "middle" },
            { size: 10000, label: "large" },
          ],
        },
      ],
      {
        width: 500,
        height: 400,
        customLadder: [100, 10000],
      },
    );
    const svg = await fs.readFile(result.outputPath, "utf8");

    expect(result).toMatchObject({
      gelId: "gel_math",
      relativePath: path.join("reports", "gels", "gel_math.gel.svg"),
      mimeType: "image/svg+xml",
      width: 500,
      height: 400,
      laneCount: 2,
      ladder: [100, 10000],
      rules: {
        migrationScale: "log10_fragment_size",
        supportedFragments: "linear_digest_or_pcr_products",
        calibrationRange: "ladder_min_to_ladder_max",
      },
    });
    expect(result.outputPath).toBe(path.join(workspaceDir, result.relativePath));
    expect(svg).toContain("gel_math");
    expect(svg).toContain("Digest");
    expect(svg).toContain("log10-scaled linear DNA fragment migration");
    expect(svg).toContain(">10 kb<");
    expect(svg).toContain(">100 bp<");
    expect(svg).not.toContain('class="lane-track"');
    expect(svg).not.toContain('stroke="#D9E1DF" stroke-width="28" stroke-linecap="round"');

    const digestBands = result.bands.filter((band) => band.laneLabel === "Digest");
    expect(digestBands.map((band) => ({ size: band.size, y: band.y }))).toEqual([
      { size: 100, y: 342 },
      { size: 1000, y: 212 },
      { size: 10000, y: 82 },
    ]);

    const second = await renderDigestGel(
      workspacePath,
      "gel_math_repeat",
      [{ label: "Digest", fragments: [{ size: 100 }, { size: 1000 }, { size: 10000 }] }],
      {
        outputPath: "reports/gels/repeat.gel.svg",
        width: 500,
        height: 400,
        customLadder: [100, 10000],
      },
    );
    const secondSvg = await fs.readFile(second.outputPath, "utf8");
    expect(secondSvg.replaceAll("gel_math_repeat", "gel_math")).toBe(svg);
  });

  it("marks fragments outside the ladder calibration range", async () => {
    const { workspacePath } = await createWorkspace();
    const result = await renderDigestGel(
      workspacePath,
      "gel_range",
      [{ label: "Default ladder digest", fragments: [{ size: 51 }, { size: 2635 }] }],
      { width: 500, height: 400 },
    );
    const svg = await fs.readFile(result.outputPath, "utf8");

    const smallBand = result.bands.find((band) => band.laneLabel === "Default ladder digest" && band.size === 51);
    expect(smallBand).toMatchObject({
      y: 342,
      outOfLadderRange: true,
      rangeWarning: "below ladder range (250-10000 bp)",
    });
    expect(svg).toContain("51 bp below ladder range (250-10000 bp)");
    expect(svg).toContain('stroke-dasharray="5 3"');

    const normalBand = result.bands.find((band) => band.laneLabel === "Default ladder digest" && band.size === 2635);
    expect(normalBand).toMatchObject({ outOfLadderRange: false });
  });

  it("renders pUC19 digest fragments generated by simulateDigest", async () => {
    const { workspacePath, moleculeId } = await importPuc19();
    const digest = await simulateDigest(workspacePath, moleculeId, ["EcoRI", "HindIII"]);
    const result = await renderDigestGel(
      workspacePath,
      "puc19_ecori_hindiii",
      [{
        label: "EcoRI + HindIII",
        fragments: digest.fragments.map((fragment) => ({ size: fragment.size })),
      }],
      { customLadder: [50, 100, 250, 500, 1000, 2000, 3000, 5000] },
    );

    expect(digest.fragments.map((fragment) => fragment.size)).toEqual([51, 2635]);
    expect(result.bands.filter((band) => band.laneLabel === "EcoRI + HindIII").map((band) => ({
      size: band.size,
      outOfLadderRange: band.outOfLadderRange,
    }))).toEqual([
      { size: 51, outOfLadderRange: false },
      { size: 2635, outOfLadderRange: false },
    ]);
  });

  it("returns artifact metadata from the tool handler", async () => {
    const { workspacePath } = await createWorkspace();
    const result = await handleRenderDigestGel({
      workspacePath,
      gelId: "handler_gel",
      lanes: [{ label: "EcoRI", fragments: [{ size: 500 }, { size: 1500 }] }],
      customLadder: [250, 500, 1000, 1500],
      width: 520,
      height: 360,
    });

    expect(result).toMatchObject({
      ok: true,
      tool: "render_digest_gel",
      artifacts: [
        {
          kind: "gel",
          mimeType: "image/svg+xml",
        },
      ],
      nextAction: {
        tool: "validate_workspace",
      },
    });
    if (!result.ok) throw new Error("expected render_digest_gel success");
    await expect(fs.stat(result.artifacts?.[0]?.path ?? "")).resolves.toBeTruthy();
  });

  it("runs through the CLI command path", async () => {
    const { workspacePath, workspaceDir } = await createWorkspace();
    const lanesPath = path.join(workspaceDir, "lanes.json");
    await fs.writeFile(lanesPath, JSON.stringify([
      { label: "CLI digest", fragments: [{ size: 250 }, { size: 1000 }] },
    ]), "utf8");

    const cli = await runCli([
      "render-digest-gel",
      workspacePath,
      "--gel-id",
      "cli_gel",
      "--lanes",
      lanesPath,
      "--custom-ladder",
      "250,1000",
    ]);

    expect(cli.exitCode).toBe(0);
    const envelope = JSON.parse(cli.stdout) as ToolResultEnvelope;
    expect(envelope).toMatchObject({
      ok: true,
      tool: "render_digest_gel",
      artifacts: [{ kind: "gel" }],
    });
  });

  it("accepts UTF-8 BOM JSON lane files through the CLI", async () => {
    const { workspacePath, workspaceDir } = await createWorkspace();
    const lanesPath = path.join(workspaceDir, "lanes-bom.json");
    await fs.writeFile(lanesPath, `\uFEFF${JSON.stringify([
      { label: "BOM digest", fragments: [{ size: 250 }, { size: 1000 }] },
    ])}`, "utf8");

    const cli = await runCli([
      "render-digest-gel",
      workspacePath,
      "--gel-id",
      "cli_bom_gel",
      "--lanes",
      lanesPath,
    ]);

    expect(cli.exitCode).toBe(0);
    expect(JSON.parse(cli.stdout)).toMatchObject({
      ok: true,
      tool: "render_digest_gel",
      artifacts: [{ kind: "gel" }],
    });
  });

  it("rejects output paths outside the workspace", async () => {
    const { workspacePath } = await createWorkspace();
    await expect(renderDigestGel(
      workspacePath,
      "escape_gel",
      [{ label: "Digest", fragments: [{ size: 1000 }] }],
      { outputPath: "../escape.gel.svg" },
    )).rejects.toMatchObject({ code: "INVALID_ARGUMENT" });
  });

  it("rejects oversized gel band inputs instead of writing a partial SVG", async () => {
    const { workspacePath } = await createWorkspace();
    await expect(renderDigestGel(
      workspacePath,
      "too_many_bands",
      [{
        label: "Too many",
        fragments: Array.from({ length: MAX_GEL_SAMPLE_BANDS + 1 }, (_, index) => ({ size: index + 1 })),
      }],
    )).rejects.toMatchObject({
      code: "INVALID_ARGUMENT",
      details: {
        totalCount: MAX_GEL_SAMPLE_BANDS + 1,
        maxBandCount: MAX_GEL_SAMPLE_BANDS,
      },
    });
  });
});
