export const packageName = "@datalox/molecule-biology";

export type {
  Alphabet,
  CoordinateSegment,
  Feature,
  GuideRecord,
  GuideRankingEvidence,
  Molecule,
  MoleculeWorkspace,
  MoleculeType,
  Primer,
  SourceFormat,
  Strand,
  Topology,
} from "./core/schema.js";

export { WORKSPACE_SCHEMA, WORKSPACE_VERSION } from "./core/schema.js";
export {
  AGENT_CONTRACT_VERSION,
  DEFERRED_SCIENTIFIC_CAVEATS,
  MCP_PROTOCOL,
  PACKAGE_NAME,
  PACKAGE_VERSION,
  PROVENANCE_BUNDLE_VERSION,
  REQUIRED_V1_TOOLS,
  buildVersionHandshake,
} from "./core/version.js";
export type { MolBioVersionHandshake } from "./core/version.js";
export {
  validateWorkspace,
  validateWorkspaceOrThrow,
  readWorkspace,
  writeWorkspaceFile,
  writeWorkspaceTransaction,
} from "./core/workspace.js";
export type { WorkspaceTransactionResult } from "./core/workspace.js";
export { getSequenceContext, listMoleculeSummaries, readMoleculeSequence } from "./core/context.js";
export type { MoleculeSummary, SequenceContext, SequenceContextOptions } from "./core/context.js";
export { closeManagedSequenceEditors, openSequenceEditor, startSequenceEditorServer } from "./ui/index.js";
export type { OpenSequenceEditorResult, SequenceEditorServer, SequenceEditorServerOptions } from "./ui/index.js";
export { sequenceDigest, normalizeSequence, reverseComplement } from "./core/sequence.js";
export { extractCircularRegion, extractSegments, validateSegments } from "./core/coordinates.js";
export { MoleculeError, WorkspaceRevisionError, WorkspaceValidationError } from "./core/errors.js";
export { parseFasta } from "./core/fasta.js";
export { parseGenBank, parseFeatureLocation } from "./core/genbank.js";
export { importSequenceFile } from "./core/import.js";
export type { ImportSequenceFileOptions, ImportSequenceFileResult } from "./core/import.js";
export { deleteFeature, deletePrimer, upsertFeature, upsertGuide, upsertPrimer } from "./core/writes.js";
export type {
  DeleteFeaturePayload,
  DeletePrimerPayload,
  UpsertGuidePayload,
  UpsertFeaturePayload,
  UpsertPrimerOptions,
  UpsertPrimerPayload,
} from "./core/writes.js";
export {
  designPrimers,
  designGrnas,
  exportGenBank,
  exportGrnaReport,
  editSequence,
  findOrfs,
  findRestrictionSites,
  assemblyFragmentsFromCutIndexes,
  compatibleRestrictionEnds,
  constructRestrictionLigationCandidates,
  extractAssemblyFragmentSequence,
  RESTRICTION_ENZYMES,
  RESTRICTION_ENZYME_TABLE_VERSION,
  MAX_DESIGN_GRNAS_CANDIDATES,
  MAX_GEL_SAMPLE_BANDS,
  MAX_GRNA_REPORT_GUIDES,
  RESTRICTION_LIGATION_PROFILES,
  RESTRICTION_LIGATION_PROFILE_VERSION,
  regeneratedRecognitionSequence,
  resolveAssemblyFragmentsForMolecule,
  resolveEnzymes,
  resolveLigationProfile,
  selectAssemblyFragment,
  simulateAssembly,
  restrictionEndFromProfile,
  renderDigestGel,
  simulateDigest,
  simulatePcr,
  STANDARD_GENETIC_CODE,
  STANDARD_GENETIC_CODE_VERSION,
  translateDnaSequence,
  translateRegion,
  alignSequences,
  exportProteinFasta,
  validateMrnaConstruct,
  parseBlastJson2,
  parseBlastPutResponse,
  parseBlastStatus,
} from "./core/deterministic.js";
export { FEATURE_COLORS, featureColor, renderPlasmidMap } from "./core/render-map.js";
export type { PlasmidMapCutSite, RenderPlasmidMapOptions, RenderPlasmidMapResult } from "./core/render-map.js";
export { formatPrimer3BoulderInput, normalizePrimerDesignOptions, parsePrimer3Output } from "./core/primer-design.js";
export type {
  DigestFragment,
  DesignedPrimer,
  DesignGrnasInput,
  DesignGrnasOptions,
  DesignGrnasResult,
  DesignPrimersInput,
  DesignPrimersOptions,
  DesignPrimersResult,
  EditSequenceInput,
  EditSequenceOperation,
  EditSequenceResult,
  ExportGenBankResult,
  ExportGrnaReportOptions,
  ExportGrnaReportResult,
  FindOrfsOptions,
  FindRestrictionSitesOptions,
  FeatureImpact,
  FeatureImpactKind,
  GelBand,
  GelFragment,
  GelLane,
  GuideCandidate,
  OrfResult,
  OrfStrand,
  PcrProduct,
  PrimerPairCandidate,
  OffTargetHit,
  RestrictionEndCompatibility,
  RestrictionEndType,
  RestrictionEnzyme,
  RestrictionFragmentEnd,
  RestrictionLigationProfile,
  RestrictionSite,
  RenderDigestGelOptions,
  RenderDigestGelResult,
  SimulateDigestResult,
  SimulatePcrResult,
  TranslateRegionOptions,
  TranslateRegionResult,
  AlignMode,
  AlignmentResult,
  AlignSequencesOptions,
  ExportProteinFastaOptions,
  ExportProteinFastaResult,
  MrnaElementType,
  MrnaTemplateType,
  MrnaElementReference,
  ValidateMrnaConstructInput,
  MrnaCheckStatus,
  MrnaCheck,
  ValidateMrnaConstructResult,
  BlastAlignment,
  BlastHit,
  BlastParsedResult,
  BlastPutResponse,
  BlastSearchStatistics,
  BlastStatus,
  BlastStrand,
  AssemblyArtifact,
  AssemblyCandidate,
  AssemblyCandidateEnd,
  AssemblyFragment,
  AssemblyFragmentSelector,
  AssemblyInputFragment,
  AssemblyJunction,
  AssemblyOrientation,
  AssemblySourceSegment,
  ConstructRestrictionLigationCandidatesInput,
  ResolvedAssemblyFragments,
  ResolveAssemblyFragmentsInput,
  SimulateAssemblyCandidate,
  SimulateAssemblyInput,
  SimulateAssemblyResult,
} from "./core/deterministic.js";
export {
  handleDeleteFeature,
  handleDeletePrimer,
  handleEditSequence,
  handleDesignGrnas,
  handleDesignPrimers,
  handleDoctor,
  handleExportGenBank,
  handleExportGrnaReport,
  handleFindOrfs,
  handleFindRestrictionSites,
  handleGetVersion,
  handleRenderDigestGel,
  handleRenderPlasmidMap,
  handleSimulateAssembly,
  handleGetSequenceContext,
  handleListMolecules,
  handleOpenSequence,
  handleOpenSequenceEditor,
  handleOpenWorkspace,
  handleReadWorkspace,
  handleReverseComplement,
  handleSimulateDigest,
  handleSimulatePcr,
  handleTranslateRegion,
  handleUpsertFeature,
  handleUpsertGrna,
  handleUpsertPrimer,
  handleValidateWorkspace,
  handleAlignSequences,
  handleExportProteinFasta,
  handleValidateMrnaConstruct,
  moleculeToolDescriptors,
  runToolHandler,
  toolFailure,
  toolFailureFromError,
  toolHandlers,
  moleculeAgentContract,
  RESPONSE_ENVELOPE_BYTE_CEILING,
  toolSuccess,
  workspacePathFromInput,
} from "./tools/index.js";
export type {
  AgentContract,
  AlignSequencesInput,
  ExportProteinFastaInput,
  ValidateMrnaConstructToolInput,
  DeleteFeatureInput,
  DeletePrimerInput,
  EditSequenceToolInput,
  DesignGrnasToolInput,
  DesignPrimersToolInput,
  EnzymeInput,
  ExportGenBankInput,
  ExportGrnaReportInput,
  ExpectedRevisionInput,
  FindOrfsInput,
  MoleculeToolInput,
  OpenSequenceInput,
  OpenSequenceEditorInput,
  ReverseComplementInput,
  SequenceContextInput,
  SimulateAssemblyToolInput,
  SimulatePcrInput,
  RenderPlasmidMapInput,
  RenderDigestGelInput,
  TranslateRegionInput,
  ToolDescriptor,
  ToolErrorEnvelope,
  ToolInputByName,
  ToolName,
  ToolNextAction,
  ToolResultEnvelope,
  ToolSuccessEnvelope,
  UpsertFeatureInput,
  UpsertGrnaInput,
  UpsertPrimerInput,
  WorkspaceInput,
} from "./tools/index.js";
export {
  createReplayRecorder,
  packReplayBundle,
  recordToolCall,
  replayToolObservation,
  runReplayDemo,
  sha256Json,
  stableJsonStringify,
  verifyReplayBundle,
} from "./replay/index.js";
export {
  callMoleculeMcpTool,
  createMoleculeMcpServer,
  listMoleculeMcpTools,
  runMoleculeMcpServer,
  toolEnvelopeToMcpResult,
} from "./mcp/index.js";
export type {
  JsonPrimitive,
  JsonValue,
  PackReplayBundleOptions,
  PackReplayBundleResult,
  ReplayBundleManifest,
  ReplayManifestRecord,
  ReplayRecorder,
  ReplayToolRecord,
  ReplayWorkspaceSummary,
  RunReplayDemoOptions,
  RunReplayDemoResult,
  VerifyReplayBundleResult,
} from "./replay/index.js";
